# Generated by Django 4.1.4 on 2022-12-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=256)),
                ('phone', models.CharField(max_length=20)),
                ('comment', models.TextField(max_length=2000)),
            ],
        ),
    ]
