# Generated by Django 4.1.4 on 2022-12-14 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_comments_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='post',
        ),
    ]
