# Generated by Django 4.1.4 on 2022-12-14 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_comments_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
