# Generated by Django 4.1.4 on 2022-12-14 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date_added',
        ),
    ]
