# Generated by Django 4.1.4 on 2022-12-14 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_comment_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
    ]
