# Generated by Django 4.1.4 on 2022-12-14 13:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='email',
            new_name='commentor_email',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='full_name',
            new_name='commentor_name',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home.post'),
            preserve_default=False,
        ),
    ]
