# Generated by Django 4.1.4 on 2023-01-24 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gellery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('image', models.ImageField(blank=True, upload_to='static/uploads/gellery')),
                ('caption', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
