# Generated by Django 4.1.4 on 2023-01-29 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_viewer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commentor_email',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='commentor_name',
        ),
    ]
