# Generated by Django 4.1.4 on 2023-01-29 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_gellery_caption_alter_gellery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gellery',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
