# Generated by Django 4.1.4 on 2023-01-29 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_gellery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='short_caption',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('ক্যাম্পাস', 'ক্যাম্পাস'), ('হল', 'হল'), ('ক্লাব', 'ক্লাব'), ('স্পোর্টস', 'স্পোর্টস'), ('এলামনাই', 'এলামনাই'), ('ব্লগ', 'ব্লগ'), ('গ্যালারি', 'গ্যালারি'), ('স্পোর্টস', 'স্পোর্টস'), ('অন্যান্য', 'অন্যান্য')], default='ক্যাম্পাস', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
