# Generated by Django 4.2.2 on 2023-06-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_remove_post_short_caption_alter_post_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=264)),
                ('email', models.EmailField(max_length=256)),
                ('phone', models.IntegerField(max_length=20)),
                ('designation', models.CharField(max_length=264)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/uploads/panels')),
            ],
        ),
    ]
